name: CI for Game

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Deps
        run: |+
          sudo apt-get update
          sudo apt-get install -y -qq clang-format build-essential
                 
      - name: Check Code style via clang-format
        run: |
          find src include -type f \( -name "*.cpp" -o -name "*.hpp" \) -exec \
            clang-format --style=file --dry-run --Werror {} +

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Conan
        run: pip install conan

      - name: Cache Conan Packages
        uses: actions/cache@v4
        with:
          path: ~/.conan2/p
          key: ${{ runner.os }}-conan-${{ hashFiles('conanfile.txt') }}
          restore-keys: |
            ${{ runner.os }}-conan-

      - name: Conan Profile Detect
        run: conan profile detect --force

      - name: Conan install
        run: |
          conan install . --output-folder=build --build=missing \
            -s build_type=Release \
            -c tools.system.package_manager:mode=install \
            -c tools.system.package_manager:sudo=True
            --deployer=direct_deploy

      - name: Debug Path (надо найти где файл расположен)
        run: find build -name "conan_toolchain.cmake"

      - name: Configure & build
        run: |
          cmake -B build \
            -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel $(nproc)
