name: CI for Game

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq \
            clang-format \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxinerama-dev \
            libxi-dev \
            libudev-dev \
            libopengl-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            mesa-common-dev \
            libflac-dev \
            libvorbis-dev \
            libopenal-dev \
            libfreetype-dev

      - name: Check Code style via clang-format
        run: find src include -type f \( -name "*.cpp" -o -name "*.hpp" \) \ -exec
          clang-format --style=file --dry-run --Werror {} +

      - name: Build via CMake
        run: |
          cmake -B build 
          cmake --build build --config Release --parallel $(nproc)
